### ISSUE TITLE
During install in a virtual env -- error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by akwala** [danny0838/PyWebScrapBook#1]
Python 3.6.7
pip 9.0.1

> $ python -m pip install -U webscrapbook
> Collecting webscrapbook
>   Downloading https://files.pythonhosted.org/packages/60/22/9737f3af6277927113e1cd51b2d9a9b7764635501bb062857687ce00c8fb/webscrapbook-0.6.0-py3-none-any.whl (43kB)
>     100% |████████████████████████████████| 51kB 1.2MB/s 
> Collecting bottle>=0.12 (from webscrapbook)
>   Downloading https://files.pythonhosted.org/packages/47/f1/666d2522c8eda26488315d7ee8882d848710b23d408ed4ced35d750d6e20/bottle-0.12.16-py3-none-any.whl (89kB)
>     100% |████████████████████████████████| 92kB 3.1MB/s 
> Collecting lxml>=4.0 (from webscrapbook)
>   Downloading https://files.pythonhosted.org/packages/35/8a/5e066949f2b40caac32c7b2a77da63ad304b5fbe869036cc3fe4a198f724/lxml-4.3.3-cp36-cp36m-manylinux1_x86_64.whl (5.7MB)
>     100% |████████████████████████████████| 5.7MB 260kB/s 
> Collecting commonmark>=0.8 (from webscrapbook)
>   Downloading https://files.pythonhosted.org/packages/a7/65/2ea45a38e8c6a0a13453c5cadcc9b725049425c8628dbe7da87b30944573/commonmark-0.9.0-py2.py3-none-any.whl (51kB)
>     100% |████████████████████████████████| 51kB 3.7MB/s 
> Collecting future (from commonmark>=0.8->webscrapbook)
>   Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
>     100% |████████████████████████████████| 829kB 1.2MB/s 
> Building wheels for collected packages: future
>   Running setup.py bdist_wheel for future ... error
>   Complete output from command /path/to/venvone/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ffb_nd4n/future/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp47pqn_dfpip-wheel- --python-tag cp36:
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: -c --help [cmd1 cmd2 ...]
>      or: -c --help-commands
>      or: -c cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for future                                                                            
>   Running setup.py clean for future                                                                           
> Failed to build future                                                                                        
> Installing collected packages: bottle, lxml, future, commonmark, webscrapbook                                 
>   Running setup.py install for future ... done                                                                
> Successfully installed bottle-0.12.16 commonmark-0.9.0 future-0.17.1 lxml-4.3.3 webscrapbook-0.6.0            
> (venvone)  
>

**Comment by danny0838** [comment]
You pip version seems too old. Try updating pip via:

    python -m pip install -U pip

If the issue still exists, try uninstalling and then reinstalling wheel:

    pip uninstall wheel
    pip install wheel

If the issue persists, please also provide your OS version for further investigation.

**Comment by akwala** [comment]
> You pip version seems too old. Try updating pip via:
> 
> ```
> python -m pip install -U pip
> ```

That was it, thanks. I'm now on pip 19.1.1. Looks like the error didn't cause the install to fail:

> $ python -m pip install -U webscrapbook
> Requirement already up-to-date: webscrapbook in ./lib/python3.6/site-packages (0.6.0)
> Requirement already satisfied, skipping upgrade: commonmark>=0.8 in ./lib/python3.6/site-packages (from webscrapbook) (0.9.0)
> Requirement already satisfied, skipping upgrade: bottle>=0.12 in ./lib/python3.6/site-packages (from webscrapbook) (0.12.16)
> Requirement already satisfied, skipping upgrade: lxml>=4.0 in ./lib/python3.6/site-packages (from webscrapbook) (4.3.3)
> Requirement already satisfied, skipping upgrade: future in ./lib/python3.6/site-packages (from commonmark>=0.8->webscrapbook) (0.17.1)
> (venv01)
