### ISSUE TITLE
提示后端服务器初始化错误: Require server app version >= 0.12.0.

### ISSUE THREAD

**Issue by eatcosmos** [danny0838/PyWebScrapBook#11]
之前还好的，这几天用不了了，不知道是不是wsb依赖的服务器版本问题
![image](https://user-images.githubusercontent.com/16435896/73620512-49b1f380-466d-11ea-9c1b-acc13047968f.png)

**Comment by danny0838** [comment]
是的，新版的瀏覽器套件開始加入檢查版本的功能，以免發生版本不相容造成的問題。請升級後端的版本。

**Comment by eatcosmos** [comment]
> 是的，新版的瀏覽器套件開始加入檢查版本的功能，以免發生版本不相容造成的問題。請升級後端的版本。

你好，怎么升级呢，已经重新pip wsb了

**Comment by danny0838** [comment]
pip install -U webscrapbook

**Comment by eatcosmos** [comment]
pip install -U webscrapbook
和
pip3 install -U webscrapbook
安装好了，还是相同的错误，可能我对python的依赖还不是很理解，macos系统的
