### ISSUE TITLE
Running server as a service (Debian)

### ISSUE THREAD

**Issue by daddy32** [danny0838/PyWebScrapBook#13]
Hello!

Is there any simple way to automatically run the server on a system boot on Debian Linux?

I've tried to create minimal systemd service file:

```bash
[Unit]
After=network.target

[Service]
ExecStart=[...]/webscrapbook_start.sh

[Install]
WantedBy=default.target
```

where webscrapbook_start.sh contains just

```bash
cd [...]/web_scraps
wsb s
```

But I'm getting following error: `webbrowser.Error: could not locate runnable browser`

Full output:

```bash
systemd[1]: Started webscrapbook.service.
webscrapbook_start.sh[31857]: WebScrapBook server starting up...
webscrapbook_start.sh[31857]: Document Root: [...]/web_scraps
webscrapbook_start.sh[31857]: Listening on http://localhost:8088
webscrapbook_start.sh[31857]: Hit Ctrl-C to shutdown.
webscrapbook_start.sh[31857]:  * Serving Flask app "webscrapbook.app" (lazy loading)
webscrapbook_start.sh[31857]:  * Environment: production
webscrapbook_start.sh[31857]:    WARNING: Do not use the development server in a production environment.
webscrapbook_start.sh[31857]:    Use a production WSGI server instead.
webscrapbook_start.sh[31857]:  * Debug mode: off
webscrapbook_start.sh[31857]: Traceback (most recent call last):
webscrapbook_start.sh[31857]:   File "/usr/local/bin/wsb", line 10, in <module>
webscrapbook_start.sh[31857]:     sys.exit(main())
webscrapbook_start.sh[31857]:   File "/usr/local/lib/python3.7/dist-packages/webscrapbook/cli.py", line 319, in main
webscrapbook_start.sh[31857]:     args['func'](args)
webscrapbook_start.sh[31857]:   File "/usr/local/lib/python3.7/dist-packages/webscrapbook/cli.py", line 49, in cmd_serve
webscrapbook_start.sh[31857]:     server.serve(args['root'])
webscrapbook_start.sh[31857]:   File "/usr/local/lib/python3.7/dist-packages/webscrapbook/server.py", line 64, in serve
webscrapbook_start.sh[31857]:     browser = webbrowser.get(config['browser']['command'] or None)
webscrapbook_start.sh[31857]:   File "/usr/lib/python3.7/webbrowser.py", line 65, in get
webscrapbook_start.sh[31857]:     raise Error("could not locate runnable browser")
webscrapbook_start.sh[31857]: webbrowser.Error: could not locate runnable browser
systemd[1]: webscrapbook.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: webscrapbook.service: Failed with result 'exit-code'.
```

**Comment by danny0838** [comment]
System service is rather platform dependent and we doesn't have a plan for it currently.

Your systemd approach seems almost right. The only problem is that your server doesn't have a built-in browser and thus encounter an error when trying to start the browser. Adjust the config file and set server.browse to false to skip starting the browser should solve the issue.

**Comment by daddy32** [comment]
Thank you. I will try as suggested and report back.

**Comment by daddy32** [comment]
Seems to work OK.

**Comment by isaaclw** [comment]
> Your systemd approach seems basically correct. The only problem is that your server doesn't have a built-in browser and thus encounters an error when trying to start the browser. Adjust the config file and set `server.browse` to `false` to skip starting the browser should solve the issue.

Could this be added to the documentation? I'm lucky I did a google search for: `"webscrapbook" webbrowser.Error: could not locate runnable browser` and wasn't disuaded by only two search results.

I'm also experimenting with running webscrapbook on a headless server.

**Comment by danny0838** [comment]
@isaaclw We'll add a patch in the next release so that failing to run a webbrowser won't interrupt server start.

As for doeumentation, I wonder where to add? It should already be clear that `wsb help config` is available for all configs... Also I don't get what's the problem about a headerless aerver, as you should able to get the same error message if you are controlling it via SSH...

Maybe we can also add a CLI option `wsb serve` to not launch the browser regardless of the config?
