### ISSUE TITLE
CSRF tokens should not be stored under document root

### ISSUE THREAD

**Issue by maxnikulin** [danny0838/PyWebScrapBook#18]
Following "Host a chrooted scrapbook" section in https://github.com/danny0838/webscrapbook/wiki/Backend#host-a-chrooted-scrapbook I configured document root for the server through `[app].root` expecting that all service files would be created outside of this directory. Later I have realized that it is possible to get list of all CSRF tokens through GET `/.wsb/server/tokens/?f=json&a=list`

Only `config.ini` is isolated by setting of `[app].root`.

It seems that tokens (and session key in the test-session branch) should be created under `root`, not under `_runtime['root']`. Likely it is better to hide locks in the non-public service directory as well.

Ideally, locally stored tokens should be hashed and the value received from client should be hashed before validation to mitigate consequences of accidentally exposed list of tokens.

`.wsb/config.ini`
```ini
[app]
root = public

[book ""]
name = scrapbook
top_dir = 
data_dir = data
tree_dir = tree
index = tree/map.html
no_tree = false
```

Actual token directory is `./public/.wsb/server/tokens`, expected path is `./wsb/server/tokens`.

**Comment by danny0838** [comment]
Quickly fixed it. Thank you for reporting.

**Comment by maxnikulin** [comment]
Thank you for the fix, I could not obtain tokens in my setup any more
