### ISSUE TITLE
無法升級後端程序到 0.23.0

### ISSUE THREAD

**Issue by yibie** [danny0838/PyWebScrapBook#24]
Mac OS 下，在 Terminal 裡輸入 wsb serve，顯示如下出錯提示：

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
> ERROR: Could not find a version that satisfies the requirement webscrapbook (from versions: none)
> ERROR: No matching distribution found for webscrapbook

我檢查過，我的 Python 版本已經升級到 3.8 了。請問到底是什麼原因呢？

**Comment by danny0838** [comment]
看起來你的系統似乎同時安裝了 python2 和 python3，這種情況下有可能 `python` 預設是執行 python2。

可以先輸入 `python --version` 看看出來的版本是 python2 或 python3。

如果是 python2，就要修改 python 使用的版本，或改為執行 `python3`，比如：

    python3 -m pip install -U webscrapbook

**Comment by yibie** [comment]
我已經輸入 python --version 檢查過，反饋的是 python 3.8.5
所以我不是很明白問題出在哪裡了

**Comment by danny0838** [comment]
那你輸入 `wsb --version` 結果是什麼？

輸入 `python -m pip install -U webscrapbook` 有錯誤訊息嗎？

**Comment by yibie** [comment]
昨天在重複嘗試了之後，已經成功將後端升級到 0.23 的版本了：
python -m pip install -U webscrapbook
Requirement already up-to-date: webscrapbook in /usr/local/lib/python3.8/site-packages (0.24.0)
Requirement already satisfied, skipping upgrade: lxml>=4.0 in /usr/local/lib/python3.8/site-packages (from webscrapbook) (4.5.2)
Requirement already satisfied, skipping upgrade: commonmark>=0.8 in /usr/local/lib/python3.8/site-packages (from webscrapbook) (0.9.1)
Requirement already satisfied, skipping upgrade: flask>=1.1 in /usr/local/lib/python3.8/site-packages (from webscrapbook) (1.1.2)
Requirement already satisfied, skipping upgrade: werkzeug>=1.0.0 in /usr/local/lib/python3.8/site-packages (from webscrapbook) (1.0.1)
Requirement already satisfied, skipping upgrade: jinja2>=2.10.1 in /usr/local/lib/python3.8/site-packages (from webscrapbook) (2.11.2)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /usr/local/lib/python3.8/site-packages (from flask>=1.1->webscrapbook) (1.1.0)
Requirement already satisfied, skipping upgrade: click>=5.1 in /usr/local/lib/python3.8/site-packages (from flask>=1.1->webscrapbook) (7.1.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from jinja2>=2.10.1->webscrapbook) (1.1.1)

但出現了另外一個問題，就是還是會出現這個錯誤提示：
后端服务器初始化错误: Require server app version >= 0.23.0.

**Comment by danny0838** [comment]
輸入 `wsb --version` 結果是輸出什麼？

**Comment by yibie** [comment]
webscrapbook 0.17.0
我搞不懂

**Comment by danny0838** [comment]
所以表示你的系統有兩個以上的 Python，並且不曉得什麼原因 wsb 是用不同版本的 Python 安裝且取得較高的優先權.....

先輸入 `which wsb` 看看是安裝在什麼路徑吧...

**Comment by yibie** [comment]
which wsb
/Library/Frameworks/Python.framework/Versions/3.8/bin/wsb

**Comment by danny0838** [comment]
那如果執行 `python -m webscrapbook --version` 結果是？

**Comment by yibie** [comment]
python -m webscrapbook --version
webscrapbook 0.24.0

**Comment by danny0838** [comment]
看來你 python 和 webscrapbook 套件安裝都沒錯，但 `wsb` 似乎是之前用不同方式安裝殘留下來的，導致版本錯誤。

暫時的解決方式是先用 `python -m webscrapbook` 代替 `wsb`，比如本來要輸入 `wsb server` 就改成 `python -m webscrapbook serve`，這樣應該可以正常執行最新版的 PyWSB 套件。另外你之前如果執行過 `wsb config -ba`，應該有產生 `.wsb/serve.py`，那麼執行 `.wsb/serve.py` 或許也是正確的版本。

至於要完整解決，就要找到之前安裝 wsb 的方式，設法把它移除，然後再用目前的 python 版本重新安裝 PyWSB，但是我沒用過 MacOS，不清楚 Python 會把東西安裝到哪裡，你可能得自行設法找答案或問人了orz

一個可以參考的方向是輸入 `which python` 看看現在的 Python 安裝在哪裡，然後再設法推敲出那個錯誤版本是怎麼來的...

**Comment by yibie** [comment]
多謝，我先嘗試一下解決方法

**Comment by danny0838** [comment]
@yibie 後來有解決嗎？

幫你問了 Pyrhon 群組，有人回覆可以試試執行以下命令刪掉舊的 wsb：

    /Library/Frameworks/Python.framework/Versions/3.8/python -m pip uninstall webscrapbook

執行完再試試 `wsb --version` 結果如何

**Comment by yibie** [comment]
不好意思，後來解決了。我記得是朋友提醒我用一個強制安裝的命令解決的。

**Comment by danny0838** [comment]
解決了就好。有印象是怎樣的命令嗎？

**Comment by yibie** [comment]
這段時間一直沒上 Github，我記得的命令是：
python3 -m pip install -U webscrapbook
