### ISSUE TITLE
无法修改配置，也无法连接后端服务器

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/PyWebScrapBook#3]
macOS 10.13 ，根据要求，安装webscrapbook ：
`pip3 install -U webscrapbook  ` 
安装以后，进入 WebScrapBook/ ，运行：
`wsb config -ba `，然后
`.wsb/serve.py`   ，提示：

Traceback (most recent call last):
  File ".wsb/serve.py", line 4, in <module>
    server.serve(os.path.dirname(os.path.dirname(__file__)))
  File "/usr/local/lib/python3.7/site-packages/webscrapbook/server.py", line 101, in serve
    os.chdir(root)

如果用 wsb serve 的话可以运行，但是还是默认设置，不知道在哪里修改设置（我在 `wsb config -ba ` 后弹出的config.ini文件修改了端口号，但是弹出的网页仍然是默认的8080端口号），火狐侧边栏也无法连接后端服务器。

**Comment by danny0838** [comment]
錯誤訊息的下半部似乎被截掉了，這樣沒有辦法除錯。麻煩再試一次並附上完整的錯誤訊息。

**Comment by woyaojizhu8** [comment]
不好意思，漏了一行。完整信息如下：
.wsb/serve.py
Traceback (most recent call last):
  File ".wsb/serve.py", line 4, in <module>
    server.serve(os.path.dirname(os.path.dirname(__file__)))
  File "/usr/local/lib/python3.7/site-packages/webscrapbook/server.py", line 101, in serve
    os.chdir(root)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by danny0838** [comment]
能否提供你的 WebScrapBook 資料夾在作業系統上的完整路徑？

**Comment by woyaojizhu8** [comment]
/Users/用户名/Downloads/WebScrapBook

**Comment by danny0838** [comment]
釋出了新版 0.6.1，請安裝新版後刪除 .wsb/serve.py 再重新產生試試。

**Comment by woyaojizhu8** [comment]
嗯，现在可以运行`.wsb/serve.py` 不报错了，但是仍然不知道如何修改设置，火狐侧边栏也无法连接后端服务器。

**Comment by danny0838** [comment]
設定問題：你修改設定時有沒有把 `;` 拿掉？那個是註解，沒拿掉整行都不會有作用的。

連接後端伺服器除了要啟動伺服器，也要在 WebScrapBook 選項設定好伺服器的路徑。如果仍然不行請提供你使用的設定值，我們再繼續研究。

**Comment by woyaojizhu8** [comment]
谢谢！去掉；后再经多次尝试，我现在能成功连接后端服务器了，但是：之前没连后端服务器，剪辑网页是保存到data文件夹，现在连接了后端服务器，剪辑网页也是保存到data文件夹，不过似乎扩展能区分直接保存的和通过后端服务器保存的条目，侧边栏只会显示通过后端服务器保存的条目。请问如何把之前保存的条目转换到这个  通过后端服务器保存的体系，让它们也能在侧边栏显示？

**Comment by danny0838** [comment]
[建立站台索引](https://github.com/danny0838/webscrapbook/wiki/(zh-tw)Indexer) 可以把之前儲存的頁面加進去。
