### ISSUE TITLE
convert sb2wsb fails, bad path to ico file

### ISSUE THREAD

**Issue by nik-gr** [danny0838/PyWebScrapBook#40]
I have scrapbook data for many years back, when I tried to convert it I got an error message of a bad path for an .ico file

The ico seems to be ok in windows explorer but on the sidebar with the legacy scrapbook addon on waterfox there is no icon for the associated scrapbooked file so I'm guessing there is some issue with it. 

Because of that the conversion fails and I cannot use my data saved with the legacy addon. Would it be possible for the conversion utility to skip such files and use some default black.ico file instead?

**Comment by danny0838** [comment]
Could you provide the associated conversion log message, and if possible, files of the item?

Also, what is the version of your PyWSB?

**Comment by nik-gr** [comment]
I should have post it here, sorry.  I am using version 0.33.3 

Error message and last INFO before it:

> INFO: Calculating tree data...
> Traceback (most recent call last):
>   File "C:\python\app\lib\site-packages\webscrapbook\scrapbook\convert\sb2wsb.py", line 397, in run
>     yield from conv.run()
>   File "C:\python\app\lib\site-packages\webscrapbook\scrapbook\convert\sb2wsb.py", line 222, in run
>     yield from self._merge_meta(book, book0)
>   File "C:\python\app\lib\site-packages\webscrapbook\scrapbook\convert\sb2wsb.py", line 291, in _merge_meta
>     meta['icon'] = pathname2url(rel_path)  # this quotes URL
>   File "nturl2path.py", line 65, in pathname2url
> OSError: Bad path: resource:\scrapbook\data\20111014193207\nooz2.ico
> CRITICAL: Bad path: resource:\scrapbook\data\20111014193207\nooz2.ico

I have a couple of more scrapbooks, I tried with one more and it was the same error and same conditions. I attach the 2 scrapbook page folders with the mentioned icos

[only1stOne.zip](https://github.com/danny0838/PyWebScrapBook/files/5892896/only1stOne.zip)
[zipped.zip](https://github.com/danny0838/PyWebScrapBook/files/5892834/zipped.zip)

**Comment by danny0838** [comment]
Could you provide the `scrapbook.rdf` of the scrapbook you are converting? Or alternatively, provide related code fragments of the items in issue, which should look like:

```
<RDF:Description RDF:about="urn:scrapbook:item20111014193207"
...
/>
```

and:

```
<RDF:Description RDF:about="urn:scrapbook:item20131129161757"
...
/>
```

**Comment by nik-gr** [comment]
Oh ok, that was quite a simple issue after all thank you. In both cases there was an error in syntax like:

    `resource://scrapbook/data/20111014193207/resource://scrapbook/data/20111014193207/nooz2.ico`

After removing the 1st part ("resource://scrapbook/data/20111014193207/"), it proceed smoothly.
Actually I had around 20 more with the same wrong syntax all of them with ID of 2014.. or older,  maybe a result of some bug of an older version of scrapbook addon? In such case I guess it won't affect many people. 
If someone has this issue can manually fix it easily with the use any editor with multi selection capability (I used vs code), multi-select all "/resource://" and with the use of ctrl+shift+left arrow or home button get all the unwanted 1st parts and delete them in one step


(I don't know if I should post this as a different question, let me know and I will)
But as I was afraid it copies everything from the legacy data folder to the new one. I have a huge amount of folders in there and I prefer to avoid that. Is there a way to create the wsb config files in the same folder where the legacy addon has the data and avoiding to copy them? I tried it with my smallest scrapbook: convert, copied wsb config files to the source folder, run the server from inside the source folder. It seems to work fine

One more question, I tried to find what are the differences between scrapbook [X] addons and webscrapbook other than the extra/different usage functionality but without success, is there some place where this is explained?

**Comment by danny0838** [comment]
> Oh ok, that was quite a simple issue after all thank you. In both cases there was an error in syntax like:
> 
> ```
> `resource://scrapbook/data/20111014193207/resource://scrapbook/data/20111014193207/nooz2.ico`
> ```
> 
> After removing the 1st part ("resource://scrapbook/data/20111014193207/"), it proceed smoothly.

Good. Seems we've done with it.

> Actually I had around 20 more with the same wrong syntax all of them with ID of 2014.. or older, maybe a result of some bug of an older version of scrapbook addon? In such case I guess it won't affect many people.

It may be related with manual editing of item icon with some legacy ScrapBook verson. But I haven't seen such issue before. It's welcome if someone has more clue.

> If someone has this issue can manually fix it easily with the use any editor with multi selection capability (I used vs code), multi-select all "/resource://" and with the use of ctrl+shift+left arrow or home button get all the unwanted 1st parts and delete them in one step

This can be easily dealt with using a text editor that supports RegExp replacing.

**Comment by danny0838** [comment]
> But as I was afraid it copies everything from the legacy data folder to the new one. I have a huge amount of folders in there and I prefer to avoid that. Is there a way to create the wsb config files in the same folder where the legacy addon has the data and avoiding to copy them? I tried it with my smallest scrapbook: convert, copied wsb config files to the source folder, run the server from inside the source folder. It seems to work fine

We have no plan to support this, as:
1. It's always safer to leave a full backup, so that the user can easily diff and check if everything works as expected, and recover everything in case anything goes wrong.
2. The conversion does not only creating wsb configs but also some in-place replacement of some content. "Creating wsb config files only" implies a rather incomplete conversion, and is not something we're going to do.

> One more question, I tried to find what are the differences between scrapbook [X] addons and webscrapbook other than the extra/different usage functionality but without success, is there some place where this is explained?

Can you be more specific about what differences you'd like to know about?

**Comment by nik-gr** [comment]
Yes of course, from what I see there is a different approach when it comes to notes (probably separators as well but I don't find them that crucial so I didn't check them out more). How about annotations and other modifications in the captured pages, are there cases where something displayed inside a captured page is not stored in the {ID} folder? In case of a use with backend server, captured as a folder and with {ID} naming format, what extra/different is saved as metadata and where? In the process of converting back/forward from legacy format are there any changes in the data folder other than the notes (and separators)?

Webscrapbook seems to be a really good replacement (and improvement) for the scrapbook addons but scraspbook was a totally great utility, worked smoothly for so many years with huge amounts of data without a flaw. If this addon stops updating and a bug/browser change make it unusable I want to be able and know how
 to move back with no issues to use scrapbook with waterfox/palemoon/..

**Comment by danny0838** [comment]
> Yes of course, from what I see there is a different approach when it comes to notes (probably separators as well but I don't find them that crucial so I didn't check them out more). 

> How about annotations and other modifications in the captured pages, are there cases where something displayed inside a captured page is not stored in the {ID} folder?

If the user configures the saved filename option to non-`%ID%`, this can happen on any captured item. Additionally, it may also be possible that the user manually adds an embedded resource that is outside the item folder.

> In case of a use with backend server, captured as a folder and with {ID} naming format, what extra/different is saved as metadata and where?

This is described in the [Data scheme](https://github.com/danny0838/webscrapbook/wiki/Scheme) wiki page. Metadata is saved in the web page HTML file as attributes of the top `HTML` element when the item is created, but aren't updated when the item metadata is modified.

> In the process of converting back/forward from legacy format are there any changes in the data folder other than the notes (and separators)?

No currently. But we may implement conversion of ScrapBook annotations for all item pages in the future. There may be some minor HTML source code change due to the difference of the implementation of the HTML/XML library of Python and major browsers.

> Webscrapbook seems to be a really good replacement (and improvement) for the scrapbook addons but scraspbook was a totally great utility, worked smoothly for so many years with huge amounts of data without a flaw. If this addon stops updating and a bug/browser change make it unusable I want to be able and know how
> to move back with no issues to use scrapbook with waterfox/palemoon/..

Note that the conversion of WebScrapBook to legacy ScrapBook is unidirectional, and some information may lose permanently. Check the description of `wsb convert wsb2sb -h` for details.

One thing not yet mentioned is that annotations created by WebScrapBook are not recognized by legacy ScrapBook. We may implement conversion of them to corresponding legacy ScrapBook annotation format in the future.

**Comment by nik-gr** [comment]
OK, thank you for the detailed reply
