### ISSUE TITLE
Linux: check.py: cache_fh: catch unknown mime-type

### ISSUE THREAD

**Issue by uhu53** [danny0838/PyWebScrapBook#42]
Yesterday I found my wsb data directory empty. I can not explain how I got there: some side effects of Fedora (python) updates, an operator fault?
I restored a fairly recent backup of the wsb data directory, restarted the wsb server, but the wsb tree in Firefox remained empty.

$ wsb check -r 
   spit some warning and errors and crashed in the function 'cache_fh' on the line (cache.py: original line: 1029):
   fdst = os.path.join(self.book.tree_dir, 'favicon', hash_ + ext)
I decorated check.py with some print statements for debugging and got the attached 'wsb-check.log'
On my system the mime-type: 'image/x-icon' is not known (anymore?), hence
   ext = mimetypes.guess_extension(mime) (line: 1028)
yields 'NONE' and the following ....join(self.book.tree_dir, 'favicon', hash_ + ext) crashes.

I inserted a workaround into cache.py:
    ...
   ext = mimetypes.guess_extension(mime) 
   if ext is NONE:
       ext = 'NONE'

Does it make sense to generally catch an unknown mime-type in check.py?

[wsb-check.log](https://github.com/danny0838/PyWebScrapBook/files/6004025/wsb-check.log)

**Comment by danny0838** [comment]
Please include `--debug` in the command and provide the log including debug information. I'm curious about what icon file it is and where did it come from. A normal capture should automatically append appropriate file extension for downloaded image files...

**Comment by uhu53** [comment]
both the logFile: 'wsb-check-debugStmnts.log', and a logFile w/o any additional statements: 'wsb-check-debug.log', an example of an offending wsb-directory: '20191222065926837.tar.gz' attached as well as my wsb config.ini .

- struggling to prepare the requested data - included another restore - my memory got more specific. 
- QUESTION: could it be that the offending data-files have been captured on a Windows machine, then transferred to the Linux server? And could it be that the mime-type:  'image/x-icon' is common in the windows world but not or less in Linux?
- My memory does not exclude that I wanted in 2018 - the period the wsb offending files are from - to share via Samba one wsb repositiory between a Windows laptop and the Linux server. I have done at the period a similar thing with firefox bookmarks.
- ASSUMING this was the case: As long as I had my wsb-tree in Firefox, the now offending wsb-data-files *.htz & -directories did no harm. Either I saw or did not see their representation in the wsb-tree or I did not notice or care.
- Only after I have lost my wsb-data-directory and had to re-index the restored wsb-data with 'wsb check' the offending files played their blocking role. 
- They sit under the '$wsb-root/data' subdirectory, whereas the files captured on the linux server itself sit directly under $wsb-root. In wsb config.ini on Linux I have the item 'root' populated with '$wsb root' and the 'data'  item empty. (this would mean too that 'wsb check' grabs everything under 'wsb root' regardless of an empty wsb 'data' item in the config.ini (?))
- I have not the nerve now, to check the Windows laptop for traces that could falsify my theory & question. The laptop migrated last year from Windows NT to Windows 10.

Thx !

[wsb-check-debug.log](https://github.com/danny0838/PyWebScrapBook/files/6012074/wsb-check-debug.log)
[wsb-check-debugStmnts.log](https://github.com/danny0838/PyWebScrapBook/files/6012075/wsb-check-debugStmnts.log)
[20191222065926837.tar.gz](https://github.com/danny0838/PyWebScrapBook/files/6012076/20191222065926837.tar.gz)
[config-ini.zip](https://github.com/danny0838/PyWebScrapBook/files/6012182/config-ini.zip)

**Comment by uhu53** [comment]
both the logFile: 'wsb-check-debugStmnts.log', and a logFile w/o any additional statements: 'wsb-check-debug.log', an example of an offending wsb-directory: '20191222065926837.tar.gz' attached as well as my wsb config.ini .

- struggling to prepare the requested data - included another restore - my memory got more specific. 
- QUESTION: could it be that the offending data-files have been captured on a Windows machine, then transferred to the Linux server? And could it be that the mime-type:  'image/x-icon' is common in the windows world but not or less in Linux?
- My memory does not exclude that I wanted in 2018 - the period the wsb offending files are from - to share via Samba one wsb repositiory between a Windows laptop and the Linux server. I have done at the period a similar thing with firefox bookmarks.
- ASSUMING this was the case: As long as I had my wsb-tree in Firefox, the now offending wsb-data-files *.htz & -directories did no harm. Either I saw or did not see their representation in the wsb-tree or I did not notice or care.
- Only after I have lost my wsb-data-directory and had to re-index the restored wsb-data with 'wsb check' the offending files played their blocking role. 
- They sit under the '$wsb-root/data' subdirectory, whereas the files captured on the linux server itself sit directly under $wsb-root. In wsb config.ini on Linux I have the item 'root' populated with '$wsb root' and the 'data'  item empty. (this would mean too that 'wsb check' grabs everything under 'wsb root' regardless of an empty wsb 'data' item in the config.ini (?))
- I have not the nerve now, to check the Windows laptop for traces that could falsify my theory & question. The laptop migrated last year from Windows NT to Windows 10.

Thx !

[wsb-check-debug.log](https://github.com/danny0838/PyWebScrapBook/files/6012074/wsb-check-debug.log)
[wsb-check-debugStmnts.log](https://github.com/danny0838/PyWebScrapBook/files/6012075/wsb-check-debugStmnts.log)
[20191222065926837.tar.gz](https://github.com/danny0838/PyWebScrapBook/files/6012076/20191222065926837.tar.gz)
[config-ini.zip](https://github.com/danny0838/PyWebScrapBook/files/6012182/config-ini.zip)

**Comment by danny0838** [comment]
This is a issue that native Python does not recognize `image/x-icon` on POSIX, and we have added it to the mapping to fix it. We also added a fix to use empty extension rather than error out if the file extension of the MIME is unknown, 0.33.4 should fixed it.

**Comment by danny0838** [comment]
I currently cannot provide more assistant for the issue of missing data directory. We haven't seen this issue before. Your config seems normal (although `book..root_dir` can generally be left empty if it is the root directory (the one where `.wsb` resides).

Be sure to backup frequently, and open an individual issue with more details if you find more clues.

**Comment by uhu53** [comment]
understood and agreed. thanks again

**Comment by danny0838** [comment]
@uhu53 PyWebScrapBook 0.33.4 has been released. Do you confirm that the issue is resolved?

**Comment by uhu53** [comment]
Yes, I can confirm, the issue with the unknown mime-type is fixed.

To check, I restored the same old wsb-data that revealed the mime-type error. 
I stumbled though over a corrupt .htz zip file. Here 'wsb check -r' crashed in the standard python zip-library /usr/lib64/python3.8/zipfile.py, meaning, the exception handling in check.py could not catch the crash in zipfile.py. 
I have no idea, what lead to the corruption of the .htz-file -- so, if one wanted to cover this type of error - if ever, I guess, one would have to check at the creation time of the .htz. 
Attached: 
- the offending .htz: 20191220035950562.htz (20191220035950562-htz.zip)
- the outcome of 'wsb check -r --debug > 20191220035950562.htz--wsb-check.log 2>&1'
- what 'unzip' meant to the .htz: 20191220035950562.htz-unzip.log
[
[20191220035950562-htz.zip](https://github.com/danny0838/PyWebScrapBook/files/6034918/20191220035950562-htz.zip)
[20191220035950562.htz--wsb-check.log](https://github.com/danny0838/PyWebScrapBook/files/6034922/20191220035950562.htz--wsb-check.log)
[20191220035950562.htz-unzip.log](https://github.com/danny0838/PyWebScrapBook/files/6034938/20191220035950562.htz-unzip.log)

**Comment by danny0838** [comment]
It seems that the htz file encounters an unexpected type of error. Can you recall how that file was created? Was that a normal capture with WSB or converted from another tool? And did that page work?

Also, it seems that you forgot to include the `.wsb/tree/favicon/` with the data directory, which would lead to loss of favicon of HTZ items.

**Comment by uhu53** [comment]
unfortunately not. As mentioned when opening the issue (#42): these files are sort of a leftover. They got my attention not within wsb in Firefox but only after the data loss and by the 'wsb check' crash.
However it's very unlikely that I did create a .htz file outside wsb.

**Comment by danny0838** [comment]
According to the error message from unzip, it seems that the htz file was recognized as a part of a multi-part zip. Did you do something like zipping a WSB normally captured folder into an htz or so?

**Comment by uhu53** [comment]
I have seen that too from the outcome of 'unzip 20191220035950562.htz'. 
Sorry, I can't imagine why I would have zipped a regular WSB folder into a .htz but I can't remember too.
So, please close the issue, if this is the only issue with a .htz-file reported  and if the outcome of the regular creation of a WSB .htz-file is checked, i.e. failures trapped.

**Comment by danny0838** [comment]
If the offending htz is created by some manual creation process if may be related to that. If you are sure that all htz files are created by normal WSB capture, there may be some unnoticed issue for WSB. Be more cautious when capturing as htz in the future and report if you see a new case of corruption.

You should be able to get the checker work by deleting the offending htz.
