### ISSUE TITLE
Move saved pages between different scrapbooks?

### ISSUE THREAD

**Issue by Tikkoneus** [danny0838/PyWebScrapBook#43]
What is the best way to move a set of saved pages out of one scrapbook into a different one? There are enough that it would be tedious to do all by hand, but I also don't want the entire second scrapbook merged into the first.

I thought about opening all pages to their source URLs (which may or may not even exist) and then saving them again, but I expect there's a way to move the local content directly?

**Comment by danny0838** [comment]
Just copy items to another scrapbook and delete them from the source acrapbook afterwards. See the related [FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#how-to-transfer-data-between-scrapbooks).
