### ISSUE TITLE
Not an issue, just asking some precision

### ISSUE THREAD

**Issue by L0rent** [danny0838/PyWebScrapBook#44]
Hi Danny.
On https://addons.mozilla.org, I am DrakeFromFrance.
On this page, https://addons.mozilla.org/fr/firefox/addon/webscrapbook/reviews/, you answered me to set server.browse to false. But I don't know how to do this. Can you explain me please?
Thank you.

**Comment by danny0838** [comment]
CD to the directory and run `wsb config -be` to generate and launch the editor to edit the config file, and edit the `browse` entry under the `[server]` section (remember to remove the `;` comment to get it work). Check `wsb config -h` for details and `wsb help config` for more details.

**Comment by L0rent** [comment]
Thank you, it works. Issue solved.

**Comment by L0rent** [comment]
Thank you, it works. Issue solved.
