### ISSUE TITLE
A quick question - seeing lots of GET / HTTP/1.1" 200 in the logs behind Traefic

### ISSUE THREAD

**Issue by gtothill** [danny0838/PyWebScrapBook#47]
Firstly thanks for this impressive browser plugin and back end server. I've spent so many years doing research and trying to faithfully store web pages - no other solution has come anywhere close to being able to do what this does -so thanks a million.
I'm using the docker PyWebScrapBook implementation and its lightning fast and reliable.
I notice in the logs frequent GET requests:

webscrapbook_1  | 127.0.0.1 - - [31/Aug/2021 13:11:36] "GET / HTTP/1.1" 200 -
webscrapbook_1  | 127.0.0.1 - - [31/Aug/2021 13:11:41] "GET / HTTP/1.1" 200 -
webscrapbook_1  | 127.0.0.1 - - [31/Aug/2021 13:11:47] "GET / HTTP/1.1" 200 -
webscrapbook_1  | 127.0.0.1 - - [31/Aug/2021 13:11:52] "GET / HTTP/1.1" 200 -
webscrapbook_1  | 127.0.0.1 - - [31/Aug/2021 13:11:57] "GET / HTTP/1.1" 200 -
webscrapbook_1  | 127.0.0.1 - - [31/Aug/2021 13:12:03] "GET / HTTP/1.1" 200 -

I wonder if this is a keep alive from the reverse proxy, which is Traefik in this case.

As I say, not a bug but I just wondered if this is likely to be expected behaviour.

Thanks,

Geoff.

**Comment by danny0838** [comment]
WSB has no background connection mechanism. You may have to check the behavior of the reverse proxy you use. Set up a localhost server connect to it directly may help troubleshooting.

**Comment by gtothill** [comment]
Thanks,
In fact it was a health check script in the docker container so all good.
Sorry to have posted this here inappropriately - but I hope it helps someone if they notice the same thing.
Cheers

Geoff.

**Comment by danny0838** [comment]
Docker for PyWSB is not released by us. Consider feedback to its developers if there's any bad, such as the request be fired too often.

**Comment by vsc55** [comment]
Information on why GET requests are received here:
https://github.com/vsc55/docker-PyWebScrapBook/issues/3
