### ISSUE TITLE
Browsing and searching file store on the PyWebScrapBook server

### ISSUE THREAD

**Issue by gtothill** [danny0838/PyWebScrapBook#50]
Apologies for the number of questions. I hope some of them and their answers will also help others.
I may be missing something significant here (and this is somewhat aligned to my previous question on thumbnails) but I dont see an easy way of browsing the files on the backend server from a normal web browser. I recognise that the server was always designed to ‘back end’ the plugin and so I understand if what I’m going to suggest / as has not been considered before.
It struck me that over time one can accumulate a huge number of saved HTML files and it would be very helpful to be able to access these from any browser - whether or not the plugin was installed.
The particular use case that I have is being able to access documents on the network from my iPad.
I can browse to the root of the server and see tree and data folders, and in the data folder all the saved files - however - they are all (necessarily) obscurely named and its not possible to find the files of interest.
Is there any way of either searching through the repository or displaying other meaningful information about the files on the server without working through the plugin?
It would be very helpful if it were to be possible because, although it wouldn’t be possible to save pages from, say the iOS browsers, it would be possible to retrieve and view pages of interest.
Thanks for any direction / comment on this,
Geoff.

**Comment by danny0838** [comment]
Run the indexer with static site pages checked, and access your scrapbook via `tree/map.html` or linked `tree/search.html`.

![圖片](https://user-images.githubusercontent.com/531417/132034170-8c76057b-f59f-472a-89bb-cb574664a706.png)

**Comment by gtothill** [comment]
Absolutely perfect!
So useful - thanks a million for all the work you do on this project and your quick and helpful replies.
This functionality is exactly what I was driving at - sorry I missed it the first time round.
Closing this issue now.
Geoff.
