### ISSUE TITLE
[Feature request]Auto start backend server when brower launched

### ISSUE THREAD

**Issue by iceout** [danny0838/PyWebScrapBook#52]
Just like another extension [scrapbee](https://addons.mozilla.org/en-US/firefox/addon/scrapbee/)

**Comment by danny0838** [comment]
We probably won't implement this since PyWSB is not meant to be local only. Such feature is not available if PyWSB is served on a remote server.

You can add the `serve.py` generated from PyWSB to system service to start it automatically when the device is booted (or when the user logs in).

**Comment by iceout** [comment]
Thanks for your reply. I'll have a try.
