### ISSUE TITLE
running indexer and then checker causes addition of index.html as captured webpage

### ISSUE THREAD

**Issue by grotesque** [danny0838/PyWebScrapBook#60]
Checker log:
```
File "work/.wsb/tree/index.html" not used as item index
Indexing unindexed files...
Added item "20230120114505743" for "work/.wsb/tree/index.html".

```
Is this config issue? I've attached my config file.

[config.zip](https://github.com/danny0838/webscrapbook/files/10465924/config.zip)

**Comment by danny0838** [comment]
This is a bug of the backend as `.wsb` under the root of a book should be ignored. 1.8.1 should fixed it.

To correct the incorrectly added files:
1. Shutdown the backend server.
2. Manually remove the entry of "work/.wsb/tree/index.html" from `.wsb/tree/meta.js` and `.wsb/tree/toc.js`.
3. Restart the backend server.
4. Refresh the WSB sidebar.
