### ISSUE TITLE
Heading for PyWebScrapBook 2.0

### ISSUE THREAD

**Issue by danny0838** [danny0838/PyWebScrapBook#65]
We are developing PyWebScrapBook 2.0 as well as the corresponding WebScrapBook 2.0, with the following features:

1\. **Server-side fulltext searching**: Although WSB supports fulltext searching, it requires the client to download all fulltext cache aforehand, which can be undesirable if the cache is large, say, hundreds to thousands MBs, especially when the backend server is hosted remotely and is accessed through a mobile device.

PyWSB 2.0 supports fulltext search at the server side, which can be invoked from the WSB 2.0 browser extension. According to some internal tests, the transmitted data size is roughly 1/30 of the total fulltext cache even when the user searches for `""` (i.e. unconditionally hit all items). The transmitted data will of course be even smaller if the user provides a more exact condition and gets less hits.

2\. **Scrapbook operation API**: PyWSB 2.0 has implemented several API for scrapbook operation (CRUD), including Python modules/classes/methods, web API, and CLI commands. WSB 2.0 has taken advantage of them and improved the performance of several scrapbook operations. The user will be able to handle scrapbook data manually or programmatically in more ways.

Although the data scheme hasn't change, there are changes of existing API, making it downward incompatible with WebScrapBook < 2.0.

Something under consideration:

1\. **Web interface for scrapbook operation**: Current PyWSB web interface supports only basic file operation, and does not support scrapbook operation like tree browsing, fulltext searching (although they can somehow be done using the static site index), item property modifying, and item moving/copying. We are planning to implement such features so that the user can access scrapbook data even without the WSB browser extension. However it is somehow challenging to build this on top of the current web interface, and we may need some help from an UI/UX expert.

2\. **Rework some WSB options as configs of a scrapbook or the backend app**: It may be desired that some options be scrapbook-specific rather than applied uniformly to the whole backend server and all scrapbooks, or be a browser extension option that may change across devices. For example, the user may want the RSS feed to show 50 items for scrapbook1 and 20 items for scrapbook2, and no RSS feed for scrapbook3, in such case the number of RSS feed items should probably be a scrapbook config.

However it would be much less flexible when a config is fixed to the server, as the user cannot modify it easily, especially when the server is hosted remotely, and we would need more evaluation on what should be done and what not.

3\. **Remove or rework export/import functionality**: It is a common practice for a legacy ScrapBook (X) user to backup or exchange scrapbook items using the export/import functionality. The export/import feature is also implemented in PyWSB; however, the user cannot simply pick a folder for exporting due to the limitation of the browser extension framework, and as a result such feature is only available through the CLI till now, making it hardly useful.

There is also an issue that importing exported items cannot perfectly reconstruct the original item tree due to the extended data tree flexibility of WSB (especially the feature that an item can be put under multiple items).

Furthermore, WSB/PyWSB also supports a much easier way to copy items between scrapbooks. To "backup" all data of an item one can simply create a new scrapbook, copy item into it, and backup the new scrapbook.

It's under consideration that the long outdated and disrepair export/import functionality should be totally removed. We'd like to know if there is still someone using it and has an idea about how to make them better/useful.

The beta version is now available at [devel-2.0 branch](https://github.com/danny0838/PyWebScrapBook/tree/devel-2.0) ([change log](https://github.com/danny0838/PyWebScrapBook/blob/devel-2.0/CHANGELOG.md)), as well as the corresponding [devel-2.0 branch of WebScrapBook](https://github.com/danny0838/webscrapbook/tree/devel-2.0).

We may consider implementing more good changes for the major revision. Welcome to take a look and provide a feedback or feature request. (Also see the [related WSB thread](https://github.com/danny0838/webscrapbook/issues/338) for discussions about the client browser extension)

----

## To install PyWSB 2.* for testing:
* Some pre-release versions are already available on PyPI. Check [the history](https://pypi.org/project/webscrapbook/#history) page to find one and install through something like `pip install webscrapbook==2.0.0b12`

* If the pre-release version is not available on PyPI:
  * Clone this repository (or visit the desired branch/tag, download the source code as a ZIP, and unpack) to anywhere (let's call it `<root>`).
  * Open CLI and change working directory to `<root>`
  * Uninstall the previously installed PyWSB: `pip uninstall webscrapbook`
  * Install from the source code: `pip install .`

* To switch back to the previously installed webscrapbook version, run `pip uninstall webscrapbook` and then `pip install webscrapbook`; or `pip install webscrapbook==<version>`.

**Comment by grotesque** [comment]
Wow thanks danny I'll check this out.
