### ISSUE TITLE
Some questions about convert file2wsb

### ISSUE THREAD

**Issue by InfiniteOpen** [danny0838/PyWebScrapBook#66]
你好，有个关于添加文章的疑问，现在的工作流是通过 singlefetcher 将页面保存为单个 html，然后通过 PyWebScrapBook 的 wbs convert file2wbs /data /web 来将 html 转换成 wbs。
现在遇到的问题是，如果我第一次导入了  /data 下的1w 个html 到 /web 目录，一切都很顺利，如果我后续要添加 200 个html 到 /web 我还能再通过 wbs convert file2wbs 这个命令吗？看上去要加 --force 的参数才能做到，但是这样会导致我之前 1w 个文件的相关数据都消失。我还想没有找到如何解决这个问题的方法
因为我觉得理想的情况应该是给wbs convert file2wbs 增加个选项允许增量添加，将 200 个html中新的文件进行转换然后添加到 /web 。

**Comment by danny0838** [comment]
我想你說的應該是 `file2wsb` 筆誤。

這個功能本來的定位就是「搬家工具」，考慮上層目錄、支援資料夾等要素之下，只要原目錄樹多了任何檔案，就可能影響整個輸出剪貼簿樹的架構，因此沒有辦法實做可靠的增量轉換。

你想要匯入新項目的功能，目前架構下大概有幾個比較接近的做法：
1. 保留所有原始檔案，每次增加新檔案就重新轉換成新剪貼簿。
2. 將增加的檔案轉換成新剪貼簿，再透過剪貼簿間複製或匯出再匯入的方式轉移至目標剪貼簿。但這麼做基本上仍無法保留目錄結構（新剪貼簿的 `xxx/yyy/zzz` 移到主剪貼簿要嘛放到根目錄下，要嘛另外產生新的 `xxx`, `yyy`, `zzz`，而非在原本的 `xxx/yyy` 下加入 `zzz`）

如果要更完整的處理，可能得自行寫腳本做相關解析了。目前研議中的 PyWSB 2.0 有提供更多相關 API ，可以參考看看，如有需要的新功能也可以提出。

不過，有個更根本的問題是，WebScrapBook 本身就有瀏覽器套件提供網頁擷取功能，為什麼不直接使用而要先用 singlefetcher (我不清楚這是什麼工具) 再匯入？如果是 WebScrapBook 本身功能有何不足，也可以提出看看。

**Comment by InfiniteOpen** [comment]
不好意思打错字了。是 file2wsb 
singlefetcher 是我用 https://github.com/gildas-lormeau/single-file-cli 魔改的一个工具，基本上就是封装了其功能，用来帮我从互联网上自动下载文章。所以手头每天都会有很多 html 添加进来，如果要改成 WebScrapBook 可能需要花费大量的时间进行重构，并且可能需要 WebScrapBook 也能支持类似 single-file-cli 功能，我觉的这个在时间成本上是不现实的。
相比于其他的 html 索引工具，PyWebScrapBook 提供了超过其他工具的搜索语法，并且导入时间也要快很多而且很稳定。目前体验下来感觉很爽。
至于你提到的两点方案,第一点对于我来说可能是不能接受的，因为一旦当数据量越来越大，消耗的时间也会越多，会产生很多无用劳动。第二点的话感觉是可以接受的，我之后会去进行尝试。
如果实在不行，我会尝试修改PyWebScrapBook源码，实现增量功能

**Comment by danny0838** [comment]
原來如此。

WSB 有提供自動擷取的功能。如果需要複雜一點的自動擷取機制，也可以另外寫一個套件並透過 API 呼叫 WSB 執行擷取（[這裡](https://github.com/danny0838/webscrapbook/wiki/External-Message-API)有初步說明）。不過這些還是需要安裝套件，如果要在完全無圖形介面的外部伺服器執行可能就沒辦法。

如果是 SingleFile 的格式，還有一個可能比較簡單的方法是把檔案放到 data 目錄，並透過 `wsb check --resolve-unindexed-files` 命令自動將其加入根目錄樹。當然其靈活性和可自訂性是相對比較差的。

**Comment by InfiniteOpen** [comment]
刚才测试了一下，先使用 wsb check --resolve-unindexed-files 将新的文件进行索引，然后再进行 fulltextcache 即可完成增量 !
