### ISSUE TITLE
Bad test: test_util_fs.TestMkDir.test_nonexist_mode() assumes no umask

### ISSUE THREAD

**Issue by ferdnyc** [danny0838/PyWebScrapBook#67]
The `TestMkDir` test `test_nonexist_mode`:

```python
    @require_posix_mode()
    def test_nonexist_mode(self):
        root = tempfile.mkdtemp(dir=tmpdir)
        dst = os.path.join(root, 'deep', 'subdir')
        util.fs.mkdir(dst, mode=0o660)
        self.assertTrue(os.path.isdir(dst))
        self.assertEqual(oct(os.stat(dst).st_mode & 0o777), oct(0o660))
```

Will fail anytime a `umask` is set, since `os.mkdir()` explicitly [applies the `umask` value when setting the mode of the created directory](https://docs.python.org/3.10/library/os.html#os.mkdir):

> On some systems, _mode_ is ignored. Where it is used, the current umask value is first masked out.

Resulting in:

```console
$ tox run -e py311
[...]
======================================================================
FAIL: test_nonexist_mode (tests.test_util_fs.TestMkDir.test_nonexist_mode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../tests/test_util_fs.py", line 806, in test_nonexist_mode
    self.assertEqual(oct(os.stat(dst).st_mode & 0o777), oct(0o660))
AssertionError: '0o640' != '0o660'
- 0o640
?    ^
+ 0o660
?    ^

```

(My interactive shell's Fedora-default `umask` is `022`.)

In theory the test could run `os.umask(0o000)` or `os.umask(0o002)` at the start of the test, though if it's going to do that it should probably capture the return value (the previous umask) and restore it after. So,

```python
    @require_posix_mode()
    def test_nonexist_mode(self):
        root = tempfile.mkdtemp(dir=tmpdir)
        dst = os.path.join(root, 'deep', 'subdir')
        old_umask = os.umask(0o000)
        util.fs.mkdir(dst, mode=0o660)
        os.umask(old_umask)
        self.assertTrue(os.path.isdir(dst))
        self.assertEqual(oct(os.stat(dst).st_mode & 0o777), oct(0o660))
```

Though, if other file/directory-creation tests are running in parallel, this probably still has the potential to mess up _their_ results.

**Comment by danny0838** [comment]
1.16.0 should have fixed it.
