### ISSUE TITLE
Bind option in config.ini is ignored

### ISSUE THREAD

**Issue by GarrisonBaird** [danny0838/PyWebScrapBook#7]
```
[server]
port = 8081
bind = 0.0.0.0
```
`Listening on http://localhost:8081`
`netstat` confirms that it's listening on `127.0.0.1`
Tested on Linux and Mac
Version 0.9.0

Thanks!

**Comment by GarrisonBaird** [comment]
https://github.com/danny0838/PyWebScrapBook/blob/09f07480e58aa3041820e592e05a1f551a692ee1/webscrapbook/server.py#L105
Replacing this line with `host = config['server']['bind'] or config['server']['host'] or ''` solves my problem

**Comment by danny0838** [comment]
The `bind` option is actually not used anymore. We'll remove the entry.

**Comment by danny0838** [comment]
Implemented in 0.9.1.
