### ISSUE TITLE
Delete file when prompted to remove scrapbook item from frontend

### ISSUE THREAD

**Issue by guidomz** [danny0838/PyWebScrapBook#70]
[This is actually a feature request]

When asked to remove a scrapbook item, WSB actually just removes the item from the list but retains the file in storage. It would be nice if users were given the option to delete the file from storage, perhaps a setting for the backend.

Thank you for this wonderful extension I've been using for more than a decade.

**Comment by danny0838** [comment]
Removed items will be moved to the recycle bin, and you can delete permanently there.

See also: https://github.com/danny0838/webscrapbook/issues/311
