### ISSUE TITLE
[已解决] pywsb2.0,关于用户身份认证和密码设定的疑惑和指导请求。

### ISSUE THREAD

**Issue by git2wing** [danny0838/PyWebScrapBook#71]
@danny0838 看到pywsb2.0的描述，很吸引人。正好随着edge插件的升级，驱动我升级pywsb由1.8到2.0.1
- 问题：pip升级后，出现无法登录，经查为config.ini配置中， "pw=明文密码“ 认证无法登录，添加 “pw_type = plain” 也无效。除非 pw=空，空密码可认证。
- 疑问：请确认pywsb2.0是否已不再支持明文密码认证？或给予配置指正，另外我通过”wsb config -ba“，看到新生成的pw配置，加密/加盐参数格式好像也有所变动，请予以确认指导？
- 建议：建议在wiki中，对身份认证，尤其是密码设定的配置格式，以及相关在线工具建议，进行指导描述。
- 以上问题，也许是我理解错误，或错漏了指导文档，则请指导和指示链接。

**Comment by git2wing** [comment]
附：升级后无效的config.ini用户认证片段如下
`
[auth "user1"]
user = aaa
pw = bbb
pw_type = plain
permission = all
`

**Comment by git2wing** [comment]
【已解决】抱歉，没有仔细读仓库文档，在PyWebScrapBook/webscrapbook/resources
/config.md中有详细说明，通过以下命令可生成强加密密码：
```
webscrapbook encrypt -m pbkdf2:sha256:600000 -s 32
```

**Comment by git2wing** [comment]
pywsb 2.0 升级后的个人感受：
- 常规使用基本无缝升级，除了config.ini配置文件，需按以上方法生成/修改pw配置参数（改进了强密码生成和校验）
- 网页保存速度加快
- 全文检索移到服务器端，速度飞快
- 新版本插件（新功能）需要2.0版本服务器，而手机端kiwi浏览器（大概率其他浏览器）老版本插件直接兼容2.0版本服务器
总之，太棒了！

**Comment by danny0838** [comment]
感謝回饋。

基本上如你發現的，基於安全性及其他考量，2.0 版以後已不再支援明文密碼。如有需要放在 config.ini 檔案（通常不建議），可以考慮寫在註解裡。

無論是在PC或手機上，WSB 2.0以後版本應該都是綁定需求 PyWSB > 2.0。如果不是這樣，應該是有搞錯安裝的版本。
