### ISSUE TITLE
Github missing latest releases

### ISSUE THREAD

**Issue by ferdnyc** [danny0838/PyWebScrapBook#78]
I see that there have been 2.3.x versions released (I assume to PyPi), but the latest release showing at https://github.com/danny0838/PyWebScrapBook/releases is still 2.2.0. Looks like the newer releases never got tagged as such.

**Comment by ferdnyc** [comment]
This matters because: While we're _permitted_ to [package from PyPi directly](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_source_files_from_pypi), it's frowned upon because many PyPi sdists are missing tests and other "auxiliary" files present in the repo. (The PyPi webscrapbook being one of those "bare-bones" sdists.) A release from the source repo is generally preferred.

**Comment by danny0838** [comment]
Regular releases besides PyPI is not (yet) planned. Some recent releases are for simple demos of packaging of exe. You can install using PIP or from the source until we do it regularly someday.

**Comment by ferdnyc** [comment]
Ah, OK. I didn't realize that even 2.3.2 was [the exact same code as 2.2.0](https://github.com/danny0838/PyWebScrapBook/compare/2.3.2...2.2.0), so there's really nothing to package. Works for me, thanks!

**Comment by danny0838** [comment]
No, there IS code change during [2.2.0 to 2.3.2](https://github.com/danny0838/PyWebScrapBook/compare/2.2.0...2.3.2). You didn't see that since you have inverted the refs.

**Comment by ferdnyc** [comment]
@danny0838 

Aargh, you're right.

The stupid thing is, that comparison was the result of going to https://github.com/danny0838/PyWebScrapBook/releases/tag/2.2.0 and then choosing **Compare -> 2.3.2** in the GitHub interface. Seems like kind of a broken feature, though I get why it would be intended primarily for comparing releases to previous ones.
